/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import static Vistas.AgregarCliente.directorio;
import javax.swing.JOptionPane;
import laboratoriotp3grupo4.Cliente;

/**
 *
 * @author alvar
 */
public class BorrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorrarCliente
     */
    public BorrarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfBusquedaTel = new javax.swing.JTextField();
        tfDniBus = new javax.swing.JTextField();
        tfApellidoBus = new javax.swing.JTextField();
        tfNombreBus = new javax.swing.JTextField();
        tfCiudadBus = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btSalirBusqueda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfBusquedaTel1 = new javax.swing.JTextField();
        tfDniBorrar = new javax.swing.JTextField();
        tfApellidoBorrar = new javax.swing.JTextField();
        tfNombreBorrar = new javax.swing.JTextField();
        tfCiudadBorrar = new javax.swing.JTextField();
        btBuscar1 = new javax.swing.JButton();
        btSalirBusqueda1 = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();

        tfBusquedaTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBusquedaTelActionPerformed(evt);
            }
        });

        btBuscar.setText("Buscar");

        btSalirBusqueda.setText("Salir");
        btSalirBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirBusquedaActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Borrar cliente");

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("BORRAR CLIENTE");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("TELEFONO:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 255));
        jLabel13.setText("DNI:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("APELLIDO:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("NOMBRE:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("CIUDAD:");

        tfBusquedaTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBusquedaTel1ActionPerformed(evt);
            }
        });

        btBuscar1.setText("Buscar");
        btBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar1ActionPerformed(evt);
            }
        });

        btSalirBusqueda1.setText("Salir");
        btSalirBusqueda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirBusqueda1ActionPerformed(evt);
            }
        });

        btBorrar.setText("Borrar");
        btBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBorrar)
                .addGap(18, 18, 18)
                .addComponent(btSalirBusqueda1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCiudadBorrar)
                            .addComponent(tfNombreBorrar)
                            .addComponent(tfApellidoBorrar)
                            .addComponent(tfDniBorrar)
                            .addComponent(tfBusquedaTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btBuscar1)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel13)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfBusquedaTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btBuscar1))
                        .addGap(28, 28, 28)
                        .addComponent(tfDniBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(tfApellidoBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(tfNombreBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(tfCiudadBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalirBusqueda1)
                            .addComponent(btBorrar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfBusquedaTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaTelActionPerformed

    private void btSalirBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalirBusquedaActionPerformed

    private void tfBusquedaTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBusquedaTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBusquedaTel1ActionPerformed

    private void btSalirBusqueda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirBusqueda1ActionPerformed
        dispose();
    }//GEN-LAST:event_btSalirBusqueda1ActionPerformed

    private void btBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar1ActionPerformed
        
        Cliente cliente;
        cliente=directorio.buscarCliente(Long.parseLong(tfBusquedaTel1.getText()));
            if (cliente==null) {
                JOptionPane.showMessageDialog(this,"El cliente no se encuentra en el directorio");
            }else{
        String documento= Long.toString(cliente.getDni());
        tfDniBorrar.setText(documento);
        tfApellidoBorrar.setText(cliente.getApellido());
        tfNombreBorrar.setText(cliente.getNombre());
        tfCiudadBorrar.setText(cliente.getCiudad());
            }
        
    }//GEN-LAST:event_btBuscar1ActionPerformed

    private void btBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarActionPerformed
        directorio.borrarCliente(Long.parseLong(tfBusquedaTel1.getText()));
    }//GEN-LAST:event_btBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar1;
    private javax.swing.JButton btSalirBusqueda;
    private javax.swing.JButton btSalirBusqueda1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JTextField tfApellidoBorrar;
    private javax.swing.JTextField tfApellidoBus;
    private javax.swing.JTextField tfBusquedaTel;
    private javax.swing.JTextField tfBusquedaTel1;
    private javax.swing.JTextField tfCiudadBorrar;
    private javax.swing.JTextField tfCiudadBus;
    private javax.swing.JTextField tfDniBorrar;
    private javax.swing.JTextField tfDniBus;
    private javax.swing.JTextField tfNombreBorrar;
    private javax.swing.JTextField tfNombreBus;
    // End of variables declaration//GEN-END:variables
}
